;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-buffer
        isearch-abort
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        kill-rectangle
        ruby-electric-matching-char
        smarter-move-beginning-of-line
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        compile-goto-error
        ido-find-file
        ido-recentf-open
        magit-status
        mouse-set-region
        ruby-electric-close-matching-char
        ruby-electric-space
        switch-to-previous-buffer
        yaml-electric-backspace
        ))
