(global-set-key [(control h)] 'delete-backward-char)

;; This are key bindings that I use
(defmacro bind (key fn)
  "shortcut for global-set-key"
  `(global-set-key (kbd ,key)
                   ;; handle unquoted function names and lambdas
                   ,(if (listp fn)
                        fn
                      `',fn)))

(bind "<f8>" 'deft)
;;(bind "<f5>" 'im/ant)
;;(bind "C-]" 'forward-paragraph)
;;(bind "C-\[" 'backward-paragraph)
(bind "C-x C-r" 'ido-recentf-open)
(bind "C-c C-d" 'im/diff-current-buffer-with-disk)
(bind "C-q" 'jw-run-test-or-spec-file)
(bind "<f2>" 'find-file-in-project)
(bind "C-c l" 'goto-line)
(bind "M-s-/" 'align)
(bind "C-l" 'textmate-select-line)
(bind "M-h" 'backward-kill-word)
(bind "M-z" 'undo)
(bind "C-a" 'back-to-indentation)
;;(bind "C-x C-f" 'ido-find-file)
(bind "C-x C-f" 'anything-for-files)
(bind "M-t" 'im/open-todo)
(bind "C-x i" 'iwb)
(bind "C-3" 'split-window-horizontally)
(bind "C-2" 'split-window-vertically)
(bind "C-1" 'switch-to-zsh)
(bind "C-M-s" 'isearch-other-window)
(bind "M-," 'tags-search)
(bind "M-?" 'tags-loop-continue)
(bind "<f6>" magit-status)
(bind "C-x k" 'im/kill-current-buffer)
(bind "M-%" 'replace-regexp)
(bind "C-." 'ido-find-file-in-tag-files)
(bind "M-\\" 'jump-to-mark)
(bind "C-\\" 'push-mark-no-activate)
(bind "M-s" 'ido-goto-symbol)
(bind "C-'" 'textmate-goto-symbol)
(bind "C-<tab>" 'bs-show)
(bind "C-x C-b" 'ido-switch-buffer)
;;(bind "C-x C-b" 'anything-for-buffers)

(bind "C-x b" 'ibuffer-bs-show)
(bind "<f11>" 'switch-full-screen)
(bind "M-/" 'hippie-expand)
(bind "M-," 'comment-or-uncomment-region)
(bind "M-." 'anything-c-etags-select)
(bind "M-l" 'highlight-lines-matching-regexp)
(bind "M-n" 'smart-symbol-go-forward)
(bind "M-p" 'smart-symbol-go-backward)
(bind "<f1>" 'help)
(bind "C-v" 'clipboard-yank)
(bind "C-x C-x" 'clipboard-kill-region)
(bind "M-m" iy-go-to-char)
(bind "C-x f" 'ido-find-file)
(bind "M-u" 'toggle-letter-case)
(bind "C-c h" 'highlight-indentation-mode)
(bind "C-c t" 'my-ido-find-tag)
(bind "C-i" 'indent-for-tab-command)

(keyboard-translate ?\C-h ?\C-?)
(global-unset-key (kbd "C-x 3"))
(global-unset-key (kbd "C-x 2"))
(global-unset-key [?\C-x ?\C-z])
(define-key global-map "\C-cc" 'org-capture)
(define-key global-map "\C-ca" 'org-agenda)
(global-set-key [(control backspace)] 'backward-kill-word)
(global-set-key [(meta delete)] 'backward-kill-word)
(define-key global-map [f9] 'bookmark-jump)
(define-key global-map [f10] 'bookmark-set)
(define-key global-map (kbd "C-+") 'text-scale-increase)
(define-key global-map (kbd "C--") 'text-scale-decrease)
(windmove-default-keybindings 'meta)
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
