(defun color-theme-im3 ()
  (interactive)
  (color-theme-install
   '(color-theme-im3
      ((background-color . "#0f141a")
      (background-mode . light)
      (border-color . "#0f0d26")
      (cursor-color . "#1016f9")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#0f0d26"))))
     (mode-line ((t (:foreground "#cfc9c9" :background "#101919"))))
     (region ((t (:background "#152d1a"))))
     (font-lock-builtin-face ((t (:foreground "#295f99"))))
     (font-lock-comment-face ((t (:foreground "#426534"))))
     (font-lock-function-name-face ((t (:foreground "#8b7df2"))))
     (font-lock-keyword-face ((t (:foreground "#3c92ec"))))
     (font-lock-string-face ((t (:foreground "#099f3b"))))
     (font-lock-type-face ((t (:foreground"#f7f42b"))))
     (font-lock-variable-name-face ((t (:foreground "#7ce74b"))))
     (minibuffer-prompt ((t (:foreground "#19cc2c" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-im3)
