(defun color-theme-im-dark ()
  (interactive)
  (color-theme-install
   '(color-theme-im-dark
      ((background-color . "#0f0f10")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#ffffff" :background "#1f1f1f"))))
     (region ((t (:background "#041b09"))))
     (font-lock-builtin-face ((t (:foreground "#0890e7"))))
     (font-lock-comment-face ((t (:foreground "#213612"))))
     (font-lock-function-name-face ((t (:foreground "#fcff42"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf"))))
     (font-lock-string-face ((t (:foreground "#91da5d"))))
     (font-lock-type-face ((t (:foreground"#4eeb47"))))
     (font-lock-variable-name-face ((t (:foreground "#8d3f67"))))
     (minibuffer-prompt ((t (:foreground "#126dce" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-im-dark)