(eval-when-compile    (require 'color-theme))
(defun color-theme-humane ()
  "Color theme by Jason F. McBrayer, created 2009-06-25."
  (interactive)
  (color-theme-install
   '(color-theme-humane
     ((background-color . "wheat")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (diary-face . diary)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline-path-completion)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
     (default ((t (:stipple nil :background "wheat" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :style released-button)))))
     (anything-isearch-match ((t (:background "Gold"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (better-fringes-bitmap ((t (:foreground "khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:foreground "DarkGoldenrod"))))
     (change-log-date ((t (:foreground "SaddleBrown"))))
     (change-log-email ((t (:foreground "DarkGoldenrod"))))
     (change-log-file ((t (:foreground "RoyalBlue"))))
     (change-log-function ((t (:foreground "DarkGoldenrod"))))
     (change-log-list ((t (:foreground "MediumPurple4"))))
     (change-log-name ((t (:foreground "CadetBlue"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:foreground "ForestGreen"))))
     (compilation-error ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "DarkGoldenrod"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:background "wheat" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "magenta4" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "blue1" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "red1" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-invalid ((t (:background "red1" :foreground "gold1"))))
     (custom-link ((t (:foreground "blue1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-visibility ((t (:foreground "blue1" :underline t :height 0.8))))
     (diary ((t (:foreground "red1"))))
     (diary-anniversary ((t (:foreground "MediumPurple4"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "DarkGoldenrod"))))
     (dired-directory ((t (:foreground "RoyalBlue"))))
     (dired-flagged ((t (:bold t :foreground "Red1" :weight bold))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "CadetBlue"))))
     (dired-marked ((t (:bold t :foreground "Red1" :weight bold))))
     (dired-perm-write ((t (:background "wheat" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (dired-symlink ((t (:foreground "MediumPurple4"))))
     (dired-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (dropdown-list-face ((t (:background "lightgoldenrod" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (dropdown-list-selection-face ((t (:background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Gold" :foreground "MediumPurple4"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "LightPink"))))
     (flymake-warnline ((t (:background "LightBlue2"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "MediumPurple"))))
     (font-lock-comment-delimiter-face ((t (:foreground "DarkGoldenrod4"))))
     (font-lock-comment-face ((t (:foreground "DarkGoldenrod4"))))
     (font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (font-lock-doc-face ((t (:foreground "SaddleBrown"))))
     (font-lock-function-name-face ((t (:foreground "RoyalBlue"))))
     (font-lock-keyword-face ((t (:foreground "MediumPurple4"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "BlueViolet"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "SaddleBrown"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "DarkOliveGreen4"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "tan"))))
     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "burlywood"))))
     (hl-line ((t (:background "burlywood"))))
     (holiday ((t (:background "pink"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "gold1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "SaddleBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "gold" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "SaddleBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-private-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-protected-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-public-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (match ((t (:background "gold1"))))
     (minibuffer-noticeable-prompt ((t (:background "gold"))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mlinks-link ((t (:foreground "blue1" :underline t))))
     (mode-line ((t (:background "burlywood4" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:background "burlywood1" :box (:line-width 2 :color "burlywood1" :style released-button)))))
     (mode-line-inactive ((t (:background "wheat4" :foreground "black" :box (:line-width -1 :color "wheat3" :style nil) :weight light))))
     (mouse ((t (nil))))
     (mumamo-background-chunk-major ((t (:background "cornsilk"))))
     (mumamo-background-chunk-submode ((t (:background "azure"))))
     (mumamo-border-face-in ((t (:italic t :bold t :foreground "Orchid" :underline t :slant italic :weight bold))))
     (mumamo-border-face-out ((t (:italic t :bold t :foreground "Orchid" :slant italic :weight bold))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "DarkGoldenrod"))))
     (nxml-attribute-prefix ((t (:foreground "Orchid"))))
     (nxml-attribute-value ((t (:foreground "SaddleBrown"))))
     (nxml-attribute-value-delimiter ((t (:foreground "SaddleBrown"))))
     (nxml-cdata-section-CDATA ((t (:foreground "Orchid"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "CadetBlue"))))
     (nxml-char-ref-number ((t (:foreground "CadetBlue"))))
     (nxml-comment-content ((t (:foreground "Firebrick"))))
     (nxml-comment-delimiter ((t (:foreground "Firebrick"))))
     (nxml-delimited-data ((t (:foreground "SaddleBrown"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "RoyalBlue"))))
     (nxml-element-prefix ((t (:foreground "Orchid"))))
     (nxml-entity-ref-delimiter ((t (:foreground "CadetBlue"))))
     (nxml-entity-ref-name ((t (:foreground "CadetBlue"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:foreground "Orchid"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "Orchid"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "DarkGoldenrod"))))
     (nxml-namespace-attribute-value ((t (:foreground "SaddleBrown"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "SaddleBrown"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "Orchid"))))
     (nxml-outline-active-indicator ((t (:background "wheat" :foreground "black" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (nxml-outline-ellipsis ((t (:bold t :background "wheat" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold ))))
     (nxml-outline-indicator ((t (:background "wheat" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal ))))
     (nxml-processing-instruction-content ((t (:foreground "SaddleBrown"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "MediumPurple4"))))
     (nxml-prolog-keyword ((t (:foreground "MediumPurple4"))))
     (nxml-prolog-literal-content ((t (:foreground "SaddleBrown"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "SaddleBrown"))))
     (nxml-ref ((t (:foreground "CadetBlue"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-column-dateline ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal ))))
     (org-agenda-clocking ((t (:background "gold3"))))
     (org-agenda-date ((t (:foreground "RoyalBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "RoyalBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-restriction-lock ((t (:background "gold1"))))
     (org-agenda-structure ((t (:foreground "RoyalBlue"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-clock-overlay ((t (:background "gold1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal ))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "MediumPurple4" :underline t))))
     (org-done  ((t (:weight bold
                             :box (:line-width 2 :color "ForestGreen"
                                               :style released-button)
                             :foreground "LightGreen" :background "ForestGreen"))))
     (org-drawer ((t (:foreground "RoyalBlue"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "MediumPurple4" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "SaddleBrown"))))
     (org-hide ((t (:foreground "wheat"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:foreground "RoyalBlue"))))
     (org-level-2 ((t (:foreground "DarkGoldenrod"))))
     (org-level-3 ((t (:foreground "MediumPurple4"))))
     (org-level-4 ((t (:foreground "Firebrick4"))))
     (org-level-5 ((t (:foreground "ForestGreen"))))
     (org-level-6 ((t (:foreground "CadetBlue"))))
     (org-level-7 ((t (:foreground "Orchid"))))
     (org-level-8 ((t (:foreground "SaddleBrown"))))
     (org-link ((t (:foreground "MediumPurple4" :underline t))))
     (org-meta-line ((t (:foreground "Firebrick"))))
     (org-mode-line-clock ((t (:inherit mode-line))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "MediumPurple4"))))
     (org-special-keyword ((t (:foreground "SaddleBrown"))))
     (org-table ((t (:foreground "RoyalBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:weight bold
                            :box (:line-width 2 :color "firebrick4"
                                              :style released-button)
                            :foreground "white" :background "Firebrick4"))))
     (org-todo-kwd-face ((t (:background "firebrick4" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-done-kwd-face ((t (:background "ForestGreen" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-project-kwd-face ((t (:background "MediumPurple" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-waiting-kwd-face ((t (:background "DarkOrange" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-someday-kwd-face ((t (:background "DodgerBlue3" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-started-kwd-face ((t (:background "DarkGoldenRod" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-cancelled-kwd-face ((t (:background "DarkOliveGreen" :foreground "wheat" :box (:line-width 2 :style released-button)))))
     (org-delegated-kwd-face ((t (:background "PaleGreen4" :foreground "wheat" :box (:line-width 2 :style released-button)))))

     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (outline-1 ((t (:foreground "RoyalBlue"))))
     (outline-2 ((t (:foreground "DarkGoldenrod"))))
     (outline-3 ((t (:foreground "MediumPurple4"))))
     (outline-4 ((t (:foreground "Firebrick4"))))
     (outline-5 ((t (:foreground "ForestGreen"))))
     (outline-6 ((t (:foreground "CadetBlue"))))
     (outline-7 ((t (:foreground "Orchid"))))
     (outline-8 ((t (:foreground "SaddleBrown"))))
     (pulse-highlight-face ((t (:background "#FFFFAA"))))
     (pulse-highlight-start-face ((t (:background "#FFFFAA"))))
     (query-replace ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (region ((t (:background "lightgoldenrod2"))))
     (rng-error ((t (:bold t :foreground "Red1" :weight bold))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (secondary-selection ((t (:background "gold1"))))
     (semantic-decoration-on-private-members-face ((t (:background "#8fffff"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#fffff8"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray90"))))
     (semantic-tag-boundary-face ((t (:overline "blue"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (sgml-namespace ((t (:foreground "Orchid"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (tabbar-button ((t (:background "gray75" :foreground "dark red" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-button-highlight ((t (:background "gray75" :foreground "gray50" :height 0.8 :family "Sans Serif"))))
     (tabbar-default ((t (:background "gray75" :foreground "gray50" :height 0.8 :family "Sans Serif"))))
     (tabbar-highlight ((t (:underline t))))
     (tabbar-selected ((t (:background "gray75" :foreground "blue" :box (:line-width 1 :color "white" :style pressed-button) :height 0.8 :family "Sans Serif"))))
     (tabbar-separator ((t (:background "gray75" :foreground "gray50" :family "Sans Serif"))))
     (tabbar-unselected ((t (:background "gray75" :foreground "gray50" :box (:line-width 1 :color "white" :style released-button) :height 0.8 :family "Sans Serif"))))
     (tmm-inactive ((t (:foreground "grey50"))))
     (todochiku-message-face ((t (:background "white" :box (:line-width 2 :color "grey40")))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (w3m-anchor ((t (:foreground "blue"))))
     (w3m-arrived-anchor ((t (:foreground "navy"))))
     (w3m-bold ((t (:bold t :weight bold))))
     (w3m-current-anchor ((t (:bold t :underline t :weight bold))))
     (w3m-form-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-mouse ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (w3m-header-line-location-content ((t (:background "Gray90" :foreground "DarkGoldenrod"))))
     (w3m-header-line-location-title ((t (:background "Gray90" :foreground "Blue"))))
     (w3m-history-current-url ((t (:background "gold1" :foreground "navy"))))
     (w3m-image ((t (:foreground "ForestGreen"))))
     (w3m-insert ((t (:foreground "purple"))))
     (w3m-italic ((t (:italic t :slant italic))))
     (w3m-strike-through ((t (:strike-through t))))
     (w3m-tab-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-mouse ((t (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected ((t (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-selected-retrieving ((t (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-retrieving ((t (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-unseen ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-underline ((t (:underline t))))
     (which-func ((t (:foreground "LightGoldenrod"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "blue1" :weight bold))))
     (woman-italic ((t (:italic t :foreground "red1" :underline t :slant italic))))
     (woman-symbol ((t (nil))))
     (woman-unknown ((t (:foreground "brown"))))
     (yas/field-highlight-face ((t (:background "DarkSeaGreen2"))))
     (yas/mirror-highlight-face ((t (:background "Lightgoldenrod2"))))))))
(add-to-list 'color-themes '(color-theme-humane  "Humane" "Jason McBrayer"))
