(defun im-light-theme ()
  (interactive)
  (color-theme-install
   '(im-light-theme
      ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#d1d1d1")
      (cursor-color . "#b1b234")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#d1d1d1"))))
     (mode-line ((t (:foreground "#ffffff" :background "#443b3b"))))
     (region ((t (:background "#bababa"))))
     (font-lock-builtin-face ((t (:foreground "#5eb061"))))
     (font-lock-comment-face ((t (:foreground "#516c51"))))
     (font-lock-function-name-face ((t (:foreground "#0a8515"))))
     (font-lock-keyword-face ((t (:foreground "#1e2ca4"))))
     (font-lock-string-face ((t (:foreground "#6aaf60"))))
     (font-lock-type-face ((t (:foreground"#20721d"))))
     (font-lock-variable-name-face ((t (:foreground "#204e65"))))
     (minibuffer-prompt ((t (:foreground "#002a99" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'im-light-theme)
