;;; axar-theme.el --- an Emacs 24 theme based on Axar (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1404996506
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Axar (tmTheme) by 
;;
;;; Code:

(deftheme axar
  "axar-theme - Created by tmtheme-to-deftheme - 2014-07-10 14:48:26 +0200")

(custom-theme-set-variables
 'axar
)

(custom-theme-set-faces
 'axar
 ;; basic theming.

 '(default ((t (:foreground "#FFFFFF" :background "#191919" ))))
 '(region  ((t (:background "#FFFFFF26"))))
 '(cursor  ((t (:background "#FFFFFF"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#474747"  :background "#303030" ))))
 '(fringe                              ((t (                       :background "#303030" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#cccccc"  :background "#303030" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#ffffff"  :background "#303030" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#616161" :background "#171717" ))))
 '(font-lock-builtin-face ((t (:foreground "#80D500"  ))))
 '(font-lock-keyword-face ((t (:foreground "#ffffff"  ))))
 '(font-lock-function-name-face ((t (:foreground "#FFFFFF"  ))))
 '(js3-function-param-face ((t (:foreground "#8AA6C1"  :italic t))))
 '(js2-function-param ((t (:foreground "#8AA6C1"  :italic t))))
 '(font-lock-string-face ((t (:foreground "#FFD700"  ))))
 '(font-lock-type-face ((t (:foreground "#FFFFFF"  :bold t))))
 '(diff-added ((t ( :background "#253B22" ))))
 '(diff-changed ((t ( :background "#4A410D" ))))
 '(diff-removed ((t ( :background "#420E09" ))))
 '(diff-removed ((t (:foreground "#F8F8F8" :background "#D03620" ))))
 '(diff-changed ((t (:foreground "#F8F8F8" :background "#C4B14A" ))))
 '(diff-added ((t (:foreground "#F8F8F8" :background "#41A83E" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#616161" :background "#171717" ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#617588"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#6b8195"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#798c9f"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8698a8"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#94a3b2"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#a2afbc"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#afbbc6"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#bdc6cf"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#cad2d9"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'axar)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; axar-theme.el ends here
