;;; bluloco-theme.el --- an Emacs 24 theme based on Bluloco (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1426149841
;;; Original author: github.com/uloco
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Bluloco (tmTheme) by github.com/uloco
;;
;;; Code:

(deftheme bluloco
  "bluloco-theme - Created by tmtheme-to-deftheme - 2015-03-12 09:44:01 +0100")

(custom-theme-set-variables
 'bluloco
)

(custom-theme-set-faces
 'bluloco
 ;; basic theming.

 '(default ((t (:foreground "#dee0df" :background "#222222" ))))
 '(region  ((t (:background "#444444"))))
 '(cursor  ((t (:background "#f8f8f0"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#484848"  :background "#353535" ))))
 '(fringe                              ((t (                       :background "#353535" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b0b5b2"  :background "#353535" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#dee0df"  :background "#353535" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#808080"  ))))
 '(font-lock-string-face ((t (:foreground "#f9c859"  ))))
 '(font-lock-builtin-face ((t (:foreground "#00b1fe"  ))))
 '(font-lock-keyword-face ((t (:foreground "#00b1fe"  ))))
 '(font-lock-type-face ((t (:foreground "#945cf7"  ))))
 '(font-lock-function-name-face ((t (:foreground "#3fc56b"  ))))
 '(js3-function-param-face ((t (:foreground "#a6d3e7"  ))))
 '(js2-function-param ((t (:foreground "#a6d3e7"  ))))
 '(font-lock-type-face ((t (  ))))
 '(font-lock-warning-face ((t (:foreground "#f8f8f0" :background "#5e5339" ))))
 '(diff-removed ((t ( :background "#be3e3c" ))))
 '(diff-added ((t ( :background "#247438" ))))
 '(diff-changed ((t ( :background "#0288c5" ))))
 '(markdown-blockquote-face ((t (:foreground "#fffcc2"  :italic t))))
 '(markdown-link-title-face ((t (:foreground "#285bf1"  :underline t))))
 '(markdown-list-face ((t (:foreground "#ffffff"  ))))
 '(git-gutter:deleted ((t ( :background "#be3e3c" ))))
 '(git-gutter:added ((t ( :background "#247438" ))))
 '(git-gutter:modified ((t ( :background "#0288C5" ))))
 '(git-gutter:untracked ((t (:foreground "#5e6060"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#808080"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#6841ad"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#734bbb"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#815cc2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8e6ec8"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#9c7fcf"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#a990d5"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#b6a2dc"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#c4b3e2"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#d1c4e9"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'bluloco)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; bluloco-theme.el ends here
