;;; brogrammer-theme.el --- an Emacs 24 theme based on Brogrammer (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1421744203
;;; Original author: Ken Wheeler
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Brogrammer (tmTheme) by Ken Wheeler
;;
;;; Code:

(deftheme brogrammer
  "brogrammer-theme - Created by tmtheme-to-deftheme - 2015-01-20 09:56:43 +0100")

(custom-theme-set-variables
 'brogrammer
)

(custom-theme-set-faces
 'brogrammer
 ;; basic theming.

 '(default ((t (:foreground "#ecf0f1" :background "#1a1a1a" ))))
 '(region  ((t (:background "#2a2a2a"))))
 '(cursor  ((t (:background "#ecf0f1"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#444545"  :background "#2f2f2f" ))))
 '(fringe                              ((t (                       :background "#2f2f2f" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b5c5c9"  :background "#2f2f2f" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#ecf0f1"  :background "#2f2f2f" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#606060"  :italic t))))
 '(font-lock-constant-face ((t (:foreground "#6c71c4"  ))))
 '(font-lock-type-face ((t (:foreground "#2ecc71"  ))))
 '(font-lock-keyword-face ((t (:foreground "#e74c3c"  :bold t))))
 '(font-lock-string-face ((t (:foreground "#f1c40f"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#e67e22"  ))))
 '(diff-removed ((t (:foreground "#F8F8F8" :background "#e74c3c" ))))
 '(diff-changed ((t (:foreground "#F8F8F8" :background "#e67e22" ))))
 '(diff-added ((t (:foreground "#F8F8F8" :background "#f1c40f" ))))
 '(git-gutter:deleted ((t (:foreground "#d7503c"  ))))
 '(git-gutter:added ((t (:foreground "#2ecc71"  ))))
 '(git-gutter:modified ((t (:foreground "#f1c40f"  ))))
 '(git-gutter:untracked ((t (:foreground "#2a2a2a"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#606060"  :italic t))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#97392a"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#a63e2e"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#b54433"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#c54a37"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#cb5644"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#cf6453"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d37162"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d77f71"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#dc8d81"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'brogrammer)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; brogrammer-theme.el ends here
