;;; easyballs-theme.el --- an Emacs 24 theme based on Easyballs (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1404996969
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Easyballs (tmTheme) by 
;;
;;; Code:

(deftheme easyballs
  "easyballs-theme - Created by tmtheme-to-deftheme - 2014-07-10 14:56:09 +0200")

(custom-theme-set-variables
 'easyballs
)

(custom-theme-set-faces
 'easyballs
 ;; basic theming.

 '(default ((t (:foreground "#D8D9D1" :background "#202122" ))))
 '(region  ((t (:background "#7f51e1"))))
 '(cursor  ((t (:background "#716fa8"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#454645"  :background "#323333" ))))
 '(fringe                              ((t (                       :background "#323333" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b0b2a2"  :background "#323333" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#d8d9d1"  :background "#323333" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#6B6F71"  :italic t))))
 '(font-lock-function-name-face ((t (:foreground "#00FAF6"  ))))
 '(font-lock-constant-face ((t (:foreground "#2DB1BC"  :italic t))))
 '(font-lock-builtin-face ((t (:foreground "#EDB272"  :italic t :bold t))))
 '(font-lock-keyword-face ((t (:foreground "#a3aad8"  ))))
 '(font-lock-string-face ((t (:foreground "#72F88F"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#d9c07f"  ))))
 '(diff-removed ((t (:foreground "#F8F8F8" :background "#D03620" ))))
 '(diff-changed ((t (:foreground "#F8F8F8" :background "#C4B14A" ))))
 '(diff-added ((t (:foreground "#F8F8F8" :background "#41A83E" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6B6F71"  :italic t))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#207d84"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#238991"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#26969e"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#2aa2ab"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#2dafb9"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#30bbc6"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#38c4cf"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#45c8d2"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#52ccd5"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'easyballs)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; easyballs-theme.el ends here
