(deftheme glacier
  "Glacier Emacs theme converted from the TextMate theme by Joey Figaro")

(custom-theme-set-faces
 'glacier
 '(trailing-whitespace ((t (:background "#252d2b"))))
 '(whitespace-trailing ((t (:background "#252d2b"))))

 '(border ((t (:background "#0d1319" ))))
 '(css-property ((t (:foreground "#ffffff" ))))
 '(css-proprietary-property ((t (:foreground "#ffffff" ))))
 '(css-selector ((t (:foreground "#ffe792" :bold t ))))
 '(cursor ((t (:background "#ffe792" ))))
 '(default ((t (:foreground "#efefef" :background "#0e151b" ))))
 '(diff-added ((t (:foreground "#f8f8f8" :background "#43ae88" ))))
 '(diff-changed ((t (:foreground "#f8f8f8" :background "#3cadd7" ))))
 '(diff-header ((t (:foreground "#f8f8f8" :italic t :background "#233345" ))))
 '(diff-hunk-header ((t (:foreground "#f8f8f8" :italic t :background "#233345" ))))
 '(diff-removed ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(font-lock-builtin-face ((t (:foreground "#d7503c" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#515c68" ))))
 '(font-lock-comment-face ((t (:foreground "#515c68" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#5eebb8" ))))
 '(font-lock-doc-face ((t (:foreground "#5eebb8" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#3cadd7"))))
 '(font-lock-keyword-face ((t (:foreground "#d7503c" :bold t ))))
 '(font-lock-negation-char-face ((t (:foreground "#d7503c" :bold t ))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#ffb454" ))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#ffb454" ))))
 '(font-lock-string-face ((t (:foreground "#ffe792" ))))
 '(font-lock-type-face ((t (:foreground "#3cadd7" :italic t ))))
 '(font-lock-variable-name-face ((t (:foreground "#d73c4d" :bold t ))))
 '(font-lock-warning-face ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(fringe ((t (:background "#0d1319" ))))
 '(highlight ((t (:background "#bd4230" :foreground "#f8f8f8"))))
 '(hl-line ((t (:background "#0d1319" ))))
 '(isearch ((t (:foreground "#f8f8f8" :background "#3cadd7" ))))
 '(isearch-fail ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(iswitchb-current-match ((t (:foreground "#f8f8f8" :background "#43ae88" ))))
 '(iswitchb-invalid-regexp ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(iswitchb-single-match ((t (:foreground "#f8f8f8" :background "#43ae88" ))))
 '(iswitchb-virtual-matches ((t (:foreground "#f8f8f8" :background "#3cadd7" ))))
 '(linum ((t (:background "#0d1319" ))))
 '(match ((t (:foreground "#f8f8f8" :background "#43ae88" ))))
 '(menu ((t (:foreground "#efefef" :background "#0e151b" ))))
 '(minibuffer-prompt ((t (:foreground "#3cadd7" ))))
 '(mode-line ((t (:background "#1b2735" ))))
 '(mode-line-buffer-id ((t (:foreground "#5eebb8" ))))
 '(mode-line-emphasis ((t (:bold t ))))
 '(mode-line-highlight ((t (:italic t ))))
 '(mode-line-inactive ((t (:background "#0d1319" ))))
 '(org-agenda-dimmed-todo-face ((t (:foreground "#515c68" ))))
 '(org-column ((t (:background "#0d1319" ))))
 '(org-column-title ((t (:background "#0d1319" ))))
 '(org-done ((t (:foreground "#f8f8f8" :background "#43ae88" ))))
 '(org-hide ((t (:foreground "#0e151b" ))))
 '(org-todo ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(org-upcoming-deadline ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(org-warning ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 '(region ((t (:background "#bd4230" ))))
 '(secondary-selection ((t (:background "#bd4230" ))))
 '(show-paren-match-face ((t (:background "#bd4230" ))))
 '(show-paren-mismatch-face ((t (:foreground "#f8f8f8" :background "#d7503c" ))))
 )

(provide-theme 'glacier)
