;;; ir-white-theme.el --- an Emacs 24 theme based on IR_White (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1414570059
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from IR_White (tmTheme) by 
;;
;;; Code:

(deftheme ir-white
  "ir-white-theme - Created by tmtheme-to-deftheme - 2014-10-29 09:07:39 +0100")

(custom-theme-set-variables
 'ir-white
)

(custom-theme-set-faces
 'ir-white
 ;; basic theming.

 '(default ((t (:foreground "#010101" :background "#FFFFFF" ))))
 '(region  ((t (:background "#E0E0ED"))))
 '(cursor  ((t (:background "#A7A7A7"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#020202"  :background "#b2b2b2" ))))
 '(fringe                              ((t (                       :background "#b2b2b2" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#010101"  :background "#e6e6e6" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#010101"  :background "#cccccc" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#898989"  ))))
 '(font-lock-type-face ((t (:foreground "#A15001"  ))))
 '(font-lock-keyword-face ((t (:foreground "#016692"  ))))
 '(font-lock-constant-face ((t (:foreground "#333366"  ))))
 '(font-lock-string-face ((t (:foreground "#009F78"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#696989"  ))))
 '(font-lock-warning-face ((t (:foreground "#A00294"  :italic t :underline t))))
 '(error ((t (:foreground "#A00294" :background "#e78ee3" ))))
 '(font-lock-preprocessor-face ((t (:foreground "#765757"  ))))
 '(diff-removed ((t (:foreground "#FFFFFF" :background "#420E09" ))))
 '(diff-changed ((t (:foreground "#FFFFFF" :background "#4A410D" ))))
 '(diff-added ((t (:foreground "#FFFFFF" :background "#253B22" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#898989"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#242448"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#27284f"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#2b2b56"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#2f2f5d"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#323364"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#36366c"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#393a73"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#3d3d7a"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#404181"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ir-white)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; ir-white-theme.el ends here
