;;; lioshi-theme.el --- an Emacs 24 theme based on lioshi (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1426150167
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from lioshi (tmTheme) by 
;;
;;; Code:

(deftheme lioshi
  "lioshi-theme - Created by tmtheme-to-deftheme - 2015-03-12 09:49:27 +0100")

(custom-theme-set-variables
 'lioshi
)

(custom-theme-set-faces
 'lioshi
 ;; basic theming.

 '(default ((t (:foreground "#C5C8C6" :background "#232324" ))))
 '(region  ((t (:background "#373B41"))))
 '(cursor  ((t (:background "#AEAFAD"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#434444"  :background "#333434" ))))
 '(fringe                              ((t (                       :background "#333434" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#9ca19e"  :background "#333434" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#c5c8c6"  :background "#333434" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#9EA19E"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#CC6666"  ))))
 '(font-lock-function-name-face ((t (:foreground "#4D9999"  ))))
 '(js3-function-param-face ((t (:foreground "#DBA639"  ))))
 '(js2-function-param ((t (:foreground "#DBA639"  ))))
 '(font-lock-builtin-face ((t (:foreground "#DE935F"  ))))
 '(font-lock-type-face ((t (:foreground "#989899"  ))))
 '(font-lock-string-face ((t (:foreground "#B5BD68"  ))))
 '(font-lock-function-name-face ((t (:foreground "#81A2BE"  ))))
 '(font-lock-keyword-face ((t (:foreground "#B294BB"  ))))
 '(diff-removed ((t (:foreground "#F8F8F8" :background "#800F00" ))))
 '(diff-changed ((t (:foreground "#F8F8F8" :background "#806F00" ))))
 '(diff-added ((t (:foreground "#F8F8F8" :background "#228000" ))))
 '(font-lock-warning-face ((t (:foreground "#CED2CF" :background "#B798BF" ))))
 '(markdown-list-face ((t (:foreground "#bf96cd"  ))))
 '(markdown-url-face ((t (:foreground "#74a468"  ))))
 '(markdown-header-face ((t (:foreground "#95652a"  :bold t))))
 '(markdown-header-rule-face ((t (:foreground "#5f91ac" :background "#042029" ))))
 '(markdown-pre-face ((t (:foreground "#DCDCDC" :background "#2C2D3A" ))))
 '(markdown-inline-code-face ((t (:foreground "#e0827e"  ))))
 '(markdown-italic-face ((t (:foreground "#65696a"  ))))
 '(markdown-blockquote-face ((t (:foreground "#0687a5"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9EA19E"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#366c6b"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#3c7776"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#418181"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#478c8c"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#4c9796"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#52a2a1"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#58abab"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#63b0b0"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6eb6b5"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lioshi)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; lioshi-theme.el ends here
