;;; sidewalk-chalk-theme.el --- an Emacs 24 theme based on Sidewalk Chalk (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1426150325
;;; Original author:
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Sidewalk Chalk (tmTheme) by
;;
;;; Code:

(deftheme sidewalk-chalk
  "sidewalk-chalk-theme - Created by tmtheme-to-deftheme - 2015-03-12 09:52:05 +0100")

(custom-theme-set-variables
 'sidewalk-chalk
)

(custom-theme-set-faces
 'sidewalk-chalk
 ;; basic theming.

 '(default ((t (:foreground "#FAFAFA" :background "#2B2D2E" ))))
 '(region  ((t (:background "#C6C6C68F"))))
 '(cursor  ((t (:background "#7F7F7F"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#545657"  :background "#404242" ))))
 '(fringe                              ((t (                       :background "#404242" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#c8c8c8"  :background "#404242" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#fafafa"  :background "#404242" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#535353"))))
 '(font-lock-string-face ((t (:foreground "#5F88B8"))))
 '(font-lock-builtin-face ((t (:foreground "#D56E26"  ))))
 '(font-lock-keyword-face ((t (:foreground "#62BA4D"  ))))
 '(font-lock-type-face ((t (  ))))
 '(font-lock-function-name-face ((t (:foreground "#A3A3A3"  ))))
 '(js3-function-param-face ((t (  ))))
 '(js2-function-param ((t (  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#535353" :background "#212223" ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#436081"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#4a698e"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#50739b"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#577da8"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#6487af"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#7191b5"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#7e9bbc"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8ba5c3"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#97afc9"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'sidewalk-chalk)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; sidewalk-chalk-theme.el ends here
