;;; text-ex-machina-theme.el --- an Emacs 24 theme based on Text Ex Machina (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1408000164
;;; Original author:
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Text Ex Machina (tmTheme) by
;;
;;; Code:

(deftheme text-ex-machina
  "text-ex-machina-theme - Created by tmtheme-to-deftheme - 2014-08-14 09:09:24 +0200")

(custom-theme-set-variables
 'text-ex-machina
)

(custom-theme-set-faces
 'text-ex-machina
 ;; basic theming.

 '(default ((t (:foreground "#E6E6E6" :background "#151515" ))))
 '(region  ((t (:background "#666666"))))
 '(cursor  ((t (:background "#F8F8F0"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#3f3f3f"  :background "#2a2a2a" ))))
 '(fringe                              ((t (                       :background "#2a2a2a" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b8b8b8"  :background "#2a2a2a" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#e6e6e6"  :background "#2a2a2a" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#333333"  ))))
 '(font-lock-string-face ((t (:foreground "#64cdff"  ))))
 '(font-lock-builtin-face ((t (:foreground "#AE81FF"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#FFFFFF"  ))))
 '(font-lock-keyword-face ((t (:foreground "#777CB2"  ))))
 '(font-lock-type-face ((t (:foreground "#CCCDFD"  :underline nil))))
 '(font-lock-function-name-face ((t (:foreground "#CCFF66"  ))))
 '(js3-function-param-face ((t (:foreground "#718a3e"  :italic t))))
 '(js2-function-param ((t (:foreground "#718a3e"  :italic t))))
 '(font-lock-warning-face ((t (:foreground "#F8F8F0" :background "#0080FF" :italic t :underline nil))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#333333"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#4f612c"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#576b30"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#5f7535"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#677f39"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#6f883d"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#779242"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#7f9c46"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#87a64a"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#8faf4f"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'text-ex-machina)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; text-ex-machina-theme.el ends here
