;;; zeus-lighter-theme.el --- an Emacs 24 theme based on Zeus - Lighter (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1460531783
;;; Original author: Zayn Ali ( https://twitter.com/zaynali53 )
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Zeus - Lighter (tmTheme) by Zayn Ali ( https://twitter.com/zaynali53 )
;;
;;; Code:

(deftheme zeus-lighter)

(custom-theme-set-faces
 'zeus-lighter
 ;; basic theming.

 '(default ((t (:foreground "#000000" :background "#f0f0f0" ))))
 '(region  ((t (:background "#8C8C8C"))))
 '(cursor  ((t (:background "#E37568"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#ccd1d4"  :background "#afafaf" ))))
 '(fringe                              ((t (                       :background "#afafaf" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#647077"  :background "#e1e1e1" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#647077"  :background "#c8c8c8" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-variable-name-face ((t (:foreground "#787878"  ))))
 '(font-lock-comment-face ((t (:foreground "#B0BEC5"  ))))
 '(font-lock-string-face ((t (:foreground "#C17A66"  ))))
 '(font-lock-keyword-face ((t (:foreground "#6B7790"  ))))
 '(font-lock-builtin-face ((t (:foreground "#F6624A"  ))))
 '(font-lock-type-face ((t (:foreground "#F6624A"  ))))
 '(font-lock-function-name-face ((t (:foreground "#F6624A"  ))))
 '(js3-function-param-face ((t (:foreground "#F6624A"  ))))
 '(js2-function-param ((t (:foreground "#F6624A"  ))))
 '(diff-removed ((t (:foreground "#00A8C6"  ))))
 '(diff-added ((t (:foreground "#A6E22E"  ))))
 '(diff-changed ((t (:foreground "#E6DB74"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#B0BEC5"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#4c5465"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#535c6f"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#5b6579"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#626d83"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#6a768d"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#737e96"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#7d889e"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8791a5"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#919aad"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'zeus-lighter)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; zeus-lighter-theme.el ends here
